export const mainMetaData = {
  home: {
    title: '포춘 이스케이프 - 당신의 운명을 발견하세요',
    description: '포춘 이스케이프에서 타로, 별자리 운세, 사주를 만나보세요!',
    keywords: '운세, 타로, 별자리, 사주',
    canonical: 'https://fortunescape.co.kr',
    ogTitle: '포춘 이스케이프 - 당신의 운명을 발견하세요',
    ogDescription: '포춘 이스케이프에서 타로와 운세를 만나보세요!',
  },
};

export const tarotMetaData = {
  tarot: {
    title: '포춘 이스케이프 - 타로 운세',
    description: '포춘 이스케이프에서 정확한 타로 운세를 경험해보세요.',
    keywords: '타로, 운세, 카드',
    canonical: 'https://fortunescape.co.kr/tarot',
    ogTitle: '포춘 이스케이프 - 타로 운세',
    ogDescription: '타로를 통해 당신의 운명을 발견하세요.',
  },
  tarotCard: {
    title: '포춘 이스케이프 - 타로 카드 선택',
    description: '포춘 이스케이프에서 타로 카드를 선택해보세요.',
    keywords: '타로, 카드 선택, 운세',
    canonical: 'https://fortunescape.co.kr/tarot/card',
    ogTitle: '포춘 이스케이프 - 타로 카드 선택',
    ogDescription: '타로 카드를 선택하고 운명을 점쳐보세요.',
  },
  tarotResult: {
    title: '포춘 이스케이프 - 타로 결과',
    description: '포춘 이스케이프에서 타로 결과를 확인해보세요.',
    keywords: '타로, 결과, 운세 해석',
    canonical: 'https://fortunescape.co.kr/tarot/result',
    ogTitle: '포춘 이스케이프 - 타로 결과',
    ogDescription: '당신의 타로 운세 결과를 확인하세요.',
  },
  shareResult: {
    title: '포춘 이스케이프 - 타로 공유하기',
    description: '포춘 이스케이프에서 타로 카드를 공유합니다.',
    keywords: '타로, 타로카드, 타로공유',
    canonical: 'https://fortunescape.co.kr/tarot/shareResult',
    ogTitle: '포춘 이스케이프 - 타로 공유하기',
    ogDescription: '타로 카드를 공유합니다.',
  },
};

export const sajuMetaData = {
  sajuHome: {
    title: '포춘 이스케이프 - 오늘의 사주',
    description: '포춘 이스케이프에서 오늘의 사주를 만나보세요.',
    keywords: '사주, 오늘의 사주, 운세',
    canonical: 'https://fortunescape.co.kr/saju',
    ogTitle: '포춘 이스케이프 - 오늘의 사주',
    ogDescription: '오늘의 사주로 하루를 준비하세요.',
  },
  sajuToday: {
    title: '포춘 이스케이프 - 오늘의 운세',
    description: '포춘 이스케이프에서 오늘의 운세를 확인해보세요.',
    keywords: '사주, 오늘의 운세, 운세',
    canonical: 'https://fortunescape.co.kr/saju/today',
    ogTitle: '포춘 이스케이프 - 오늘의 운세',
    ogDescription: '오늘의 운세를 확인하고 하루를 계획하세요.',
  },
  sajuTomorrow: {
    title: '포춘 이스케이프 - 내일의 운세',
    description: '포춘 이스케이프에서 내일의 운세를 확인하세요.',
    keywords: '사주, 내일의 운세, 운세',
    canonical: 'https://fortunescape.co.kr/saju/tomorrow',
    ogTitle: '포춘 이스케이프 - 내일의 운세',
    ogDescription: '내일의 운세로 미리 하루를 준비하세요.',
  },
  sajuResult: {
    title: '포춘 이스케이프 - 사주 결과',
    description: '포춘 이스케이프에서 사주 결과를 확인해보세요.',
    keywords: '사주 결과, 운세 해석',
    canonical: 'https://fortunescape.co.kr/saju/result',
    ogTitle: '포춘 이스케이프 - 사주 결과',
    ogDescription: '사주 결과를 통해 인생의 방향을 점쳐보세요.',
  },
  sajuSelect: {
    title: '포춘 이스케이프 - 사주 선택',
    description: '포춘 이스케이프에서 사주를 선택하세요.',
    keywords: '사주 선택, 운세',
    canonical: 'https://fortunescape.co.kr/saju/select',
    ogTitle: '포춘 이스케이프 - 사주 선택',
    ogDescription: '사주를 선택하여 당신의 운세를 확인하세요.',
  },
  sajuYear: {
    title: '포춘 이스케이프 - 연도별 사주',
    description: '포춘 이스케이프에서 연도별 사주를 확인해보세요.',
    keywords: '연도별 사주, 운세',
    canonical: 'https://fortunescape.co.kr/saju/year',
    ogTitle: '포춘 이스케이프 - 연도별 사주',
    ogDescription: '연도별 사주로 미래를 준비하세요.',
  },
  sajuTojeong: {
    title: '포춘 이스케이프 - 토정비결',
    description: '포춘 이스케이프에서 토정비결을 확인하세요.',
    keywords: '토정비결, 운세, 사주',
    canonical: 'https://fortunescape.co.kr/saju/tojeong',
    ogTitle: '포춘 이스케이프 - 토정비결',
    ogDescription: '토정비결로 당신의 운명을 예측하세요.',
  },
  sajuTraditional: {
    title: '포춘 이스케이프 - 전통 사주',
    description: '포춘 이스케이프에서 전통 사주를 확인하세요.',
    keywords: '전통 사주, 운세',
    canonical: 'https://fortunescape.co.kr/saju/traditional',
    ogTitle: '포춘 이스케이프 - 전통 사주',
    ogDescription: '전통 사주로 깊이 있는 운세를 만나보세요.',
  },
};

export const authMetaData = {
  login: {
    title: '포춘 이스케이프 - 로그인',
    description: '포춘 이스케이프에 로그인하여 다양한 운세와 타로를 경험하세요.',
    keywords: '로그인, 운세, 타로',
    canonical: 'https://fortunescape.co.kr/login',
    ogTitle: '포춘 이스케이프 - 로그인',
    ogDescription: '포춘 이스케이프에 로그인하고 특별한 운세를 만나보세요.',
  },
  auth: {
    title: '포춘 이스케이프 - 인증',
    description: '포춘 이스케이프에서 인증을 진행하세요.',
    keywords: '인증, 계정 관리',
    canonical: 'https://fortunescape.co.kr/auth',
    ogTitle: '포춘 이스케이프 - 인증',
    ogDescription: '계정 인증을 통해 포춘 이스케이프를 이용하세요.',
  },
  signup: {
    title: '포춘 이스케이프 - 회원가입',
    description: '포춘 이스케이프에 가입하고 다양한 서비스를 경험하세요.',
    keywords: '회원가입, 운세, 타로',
    canonical: 'https://fortunescape.co.kr/signup',
    ogTitle: '포춘 이스케이프 - 회원가입',
    ogDescription: '지금 포춘 이스케이프에 가입하고 운세의 세계로 초대합니다.',
  },
  termsOfUse: {
    title: '포춘 이스케이프 - 이용 약관',
    description: '포춘 이스케이프의 이용 약관을 확인하세요.',
    keywords: '이용 약관, 서비스 정책',
    canonical: 'https://fortunescape.co.kr/termsOfUse',
    ogTitle: '포춘 이스케이프 - 이용 약관',
    ogDescription: '포춘 이스케이프의 이용 약관을 확인하세요.',
  },
  personalInformationTerms: {
    title: '포춘 이스케이프 - 개인정보 처리방침',
    description: '포춘 이스케이프의 개인정보 처리방침을 확인하세요.',
    keywords: '개인정보, 처리방침, 데이터 보호',
    canonical: 'https://fortunescape.co.kr/personalInformationTerms',
    ogTitle: '포춘 이스케이프 - 개인정보 처리방침',
    ogDescription: '포춘 이스케이프의 개인정보 처리방침을 읽어보세요.',
  },
  marketingUseAgreement: {
    title: '포춘 이스케이프 - 마케팅 이용 동의',
    description: '포춘 이스케이프의 마케팅 이용 동의를 확인하세요.',
    keywords: '마케팅, 이용 동의, 프로모션',
    canonical: 'https://fortunescape.co.kr/marketingUseAgreement',
    ogTitle: '포춘 이스케이프 - 마케팅 이용 동의',
    ogDescription: '포춘 이스케이프의 마케팅 이용 동의 내용을 확인하세요.',
  },
};

export const myPageMetaData = {
  myPage: {
    title: '포춘 이스케이프 - 마이 페이지',
    description: '포춘 이스케이프의 마이 페이지에서 개인 설정을 확인하고 관리하세요.',
    keywords: '마이 페이지, 개인 설정, 사용자 정보',
    canonical: 'https://fortunescape.co.kr/myPage',
    ogTitle: '포춘 이스케이프 - 마이 페이지',
    ogDescription: '마이 페이지에서 북마크, 설정 등을 관리하세요.',
  },
  settings: {
    title: '포춘 이스케이프 - 설정',
    description: '포춘 이스케이프에서 개인 설정을 관리하세요.',
    keywords: '설정, 개인 설정, 사용자 정보',
    canonical: 'https://fortunescape.co.kr/myPage/settings',
    ogTitle: '포춘 이스케이프 - 설정',
    ogDescription: '개인 설정을 통해 더 나은 경험을 만들어보세요.',
  },
  account: {
    title: '포춘 이스케이프 - 계정 관리',
    description: '포춘 이스케이프에서 계정 정보를 확인하고 관리하세요.',
    keywords: '계정 관리, 사용자 정보',
    canonical: 'https://fortunescape.co.kr/myPage/account',
    ogTitle: '포춘 이스케이프 - 계정 관리',
    ogDescription: '계정 정보를 관리하고 최신 상태로 유지하세요.',
  },
  language: {
    title: '포춘 이스케이프 - 언어 설정',
    description: '포춘 이스케이프에서 언어 설정을 변경하세요.',
    keywords: '언어 설정, 다국어 지원',
    canonical: 'https://fortunescape.co.kr/myPage/language',
    ogTitle: '포춘 이스케이프 - 언어 설정',
    ogDescription: '언어 설정을 통해 원하는 언어로 서비스를 이용하세요.',
  },
  notice: {
    title: '포춘 이스케이프 - 공지사항',
    description: '포춘 이스케이프의 최신 공지사항을 확인하세요.',
    keywords: '공지사항, 최신 정보',
    canonical: 'https://fortunescape.co.kr/myPage/notice',
    ogTitle: '포춘 이스케이프 - 공지사항',
    ogDescription: '서비스와 관련된 중요한 정보를 확인하세요.',
  },
  bookmark: {
    title: '포춘 이스케이프 - 북마크',
    description: '포춘 이스케이프에서 북마크한 콘텐츠를 확인하세요.',
    keywords: '북마크, 즐겨찾기',
    canonical: 'https://fortunescape.co.kr/myPage/bookmark',
    ogTitle: '포춘 이스케이프 - 북마크',
    ogDescription: '즐겨찾기한 콘텐츠를 편리하게 관리하세요.',
  },
  bookmarkTarotCards: {
    title: '포춘 이스케이프 - 북마크 타로 카드',
    description: '포춘 이스케이프에서 북마크한 타로 카드를 확인하세요.',
    keywords: '타로 카드, 북마크',
    canonical: 'https://fortunescape.co.kr/myPage/bookmarkTarotCards',
    ogTitle: '포춘 이스케이프 - 북마크 타로 카드',
    ogDescription: '북마크한 타로 카드를 확인하고 분석하세요.',
  },
  bookmarkFortuneCards: {
    title: '포춘 이스케이프 - 북마크 운세 카드',
    description: '포춘 이스케이프에서 북마크한 운세 카드를 확인하세요.',
    keywords: '운세 카드, 북마크',
    canonical: 'https://fortunescape.co.kr/myPage/bookmarkFortuneCards',
    ogTitle: '포춘 이스케이프 - 북마크 운세 카드',
    ogDescription: '북마크한 운세 카드를 관리하세요.',
  },
  bookmarkDreamCards: {
    title: '포춘 이스케이프 - 북마크 해몽 카드',
    description: '포춘 이스케이프에서 북마크한 해몽 카드를 확인하세요.',
    keywords: '해몽 카드, 북마크',
    canonical: 'https://fortunescape.co.kr/myPage/bookmarkDreamCards',
    ogTitle: '포춘 이스케이프 - 북마크 해몽 카드',
    ogDescription: '북마크한 해몽 카드를 분석하세요.',
  },
  bookmarkNamingCards: {
    title: '포춘 이스케이프 - 북마크 작명 카드',
    description: '포춘 이스케이프에서 북마크한 작명 카드를 확인하세요.',
    keywords: '작명 카드, 북마크',
    canonical: 'https://fortunescape.co.kr/myPage/bookmarkNamingCards',
    ogTitle: '포춘 이스케이프 - 북마크 작명 카드',
    ogDescription: '북마크한 작명 카드를 확인하세요.',
  },
  withdrawal: {
    title: '포춘 이스케이프 - 계정 탈퇴',
    description: '포춘 이스케이프에서 계정을 탈퇴할 수 있습니다.',
    keywords: '계정 탈퇴, 사용자 정보',
    canonical: 'https://fortunescape.co.kr/myPage/withdrawal',
    ogTitle: '포춘 이스케이프 - 계정 탈퇴',
    ogDescription: '계정을 탈퇴하고 더 이상 서비스를 이용하지 않습니다.',
  },
};

export const namingMetaData = {
  namingHome: {
    title: '포춘 이스케이프 - 작명 홈',
    description: '포춘 이스케이프에서 이름 작명 서비스를 이용해보세요.',
    keywords: '작명, 이름 작명, 운세',
    canonical: 'https://fortunescape.co.kr/naming',
    ogTitle: '포춘 이스케이프 - 작명 홈',
    ogDescription: '새로운 이름으로 당신의 운명을 바꿔보세요.',
  },
  namingResult: {
    title: '포춘 이스케이프 - 작명 결과',
    description: '포춘 이스케이프에서 이름 작명 결과를 확인하세요.',
    keywords: '작명 결과, 이름 해석',
    canonical: 'https://fortunescape.co.kr/naming/result',
    ogTitle: '포춘 이스케이프 - 작명 결과',
    ogDescription: '작명 결과를 통해 이름의 의미를 알아보세요.',
  },
};

export const dreamMetaData = {
  dreamHome: {
    title: '포춘 이스케이프 - 꿈 해몽 홈',
    description: '포춘 이스케이프에서 꿈 해몽 서비스를 이용해보세요.',
    keywords: '꿈 해몽, 해몽 서비스, 운세',
    canonical: 'https://fortunescape.co.kr/dream',
    ogTitle: '포춘 이스케이프 - 꿈 해몽 홈',
    ogDescription: '당신의 꿈이 담고 있는 의미를 해석해보세요.',
  },
  dreamResult: {
    title: '포춘 이스케이프 - 꿈 해몽 결과',
    description: '포춘 이스케이프에서 꿈 해몽 결과를 확인하세요.',
    keywords: '꿈 해몽 결과, 꿈 해석',
    canonical: 'https://fortunescape.co.kr/dream/result',
    ogTitle: '포춘 이스케이프 - 꿈 해몽 결과',
    ogDescription: '꿈의 결과를 통해 운명을 점쳐보세요.',
  },
};
